/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsInt,
  IsDate,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { GraphQLBigInt } from "../../util/GraphQLBigInt";
import { Type } from "class-transformer";
import { TransactionWhereUniqueInput } from "../../transaction/base/TransactionWhereUniqueInput";
import { AssetDescriptionCreateNestedManyWithoutAssetsInput } from "./AssetDescriptionCreateNestedManyWithoutAssetsInput";

@InputType()
class AssetCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  identifier!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  metadata!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  owner!: string;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => GraphQLBigInt)
  supply!: bigint;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  verifiedAt?: Date | null;

  @ApiProperty({
    required: true,
    type: () => TransactionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TransactionWhereUniqueInput)
  @Field(() => TransactionWhereUniqueInput)
  createdTransaction!: TransactionWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => AssetDescriptionCreateNestedManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => AssetDescriptionCreateNestedManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => AssetDescriptionCreateNestedManyWithoutAssetsInput, {
    nullable: true,
  })
  descriptions?: AssetDescriptionCreateNestedManyWithoutAssetsInput;
}

export { AssetCreateInput as AssetCreateInput };
