/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AssetService } from "../asset.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AssetCreateInput } from "./AssetCreateInput";
import { AssetWhereInput } from "./AssetWhereInput";
import { AssetWhereUniqueInput } from "./AssetWhereUniqueInput";
import { AssetFindManyArgs } from "./AssetFindManyArgs";
import { AssetUpdateInput } from "./AssetUpdateInput";
import { Asset } from "./Asset";
import { AssetDescriptionFindManyArgs } from "../../assetDescription/base/AssetDescriptionFindManyArgs";
import { AssetDescription } from "../../assetDescription/base/AssetDescription";
import { AssetDescriptionWhereUniqueInput } from "../../assetDescription/base/AssetDescriptionWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AssetControllerBase {
  constructor(
    protected readonly service: AssetService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Asset })
  @nestAccessControl.UseRoles({
    resource: "Asset",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: AssetCreateInput): Promise<Asset> {
    return await this.service.create({
      data: {
        ...data,

        createdTransaction: {
          connect: data.createdTransaction,
        },
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        identifier: true,
        metadata: true,
        name: true,
        owner: true,
        supply: true,
        verifiedAt: true,

        createdTransaction: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Asset] })
  @ApiNestedQuery(AssetFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Asset",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Asset[]> {
    const args = plainToClass(AssetFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        identifier: true,
        metadata: true,
        name: true,
        owner: true,
        supply: true,
        verifiedAt: true,

        createdTransaction: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Asset })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Asset",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: AssetWhereUniqueInput
  ): Promise<Asset | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        identifier: true,
        metadata: true,
        name: true,
        owner: true,
        supply: true,
        verifiedAt: true,

        createdTransaction: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Asset })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Asset",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: AssetWhereUniqueInput,
    @common.Body() data: AssetUpdateInput
  ): Promise<Asset | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          createdTransaction: {
            connect: data.createdTransaction,
          },
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          identifier: true,
          metadata: true,
          name: true,
          owner: true,
          supply: true,
          verifiedAt: true,

          createdTransaction: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Asset })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Asset",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: AssetWhereUniqueInput
  ): Promise<Asset | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          identifier: true,
          metadata: true,
          name: true,
          owner: true,
          supply: true,
          verifiedAt: true,

          createdTransaction: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/descriptions")
  @ApiNestedQuery(AssetDescriptionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AssetDescription",
    action: "read",
    possession: "any",
  })
  async findManyDescriptions(
    @common.Req() request: Request,
    @common.Param() params: AssetWhereUniqueInput
  ): Promise<AssetDescription[]> {
    const query = plainToClass(AssetDescriptionFindManyArgs, request.query);
    const results = await this.service.findDescriptions(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        type: true,
        value: true,

        asset: {
          select: {
            id: true,
          },
        },

        transaction: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/descriptions")
  @nestAccessControl.UseRoles({
    resource: "Asset",
    action: "update",
    possession: "any",
  })
  async connectDescriptions(
    @common.Param() params: AssetWhereUniqueInput,
    @common.Body() body: AssetDescriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      descriptions: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/descriptions")
  @nestAccessControl.UseRoles({
    resource: "Asset",
    action: "update",
    possession: "any",
  })
  async updateDescriptions(
    @common.Param() params: AssetWhereUniqueInput,
    @common.Body() body: AssetDescriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      descriptions: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/descriptions")
  @nestAccessControl.UseRoles({
    resource: "Asset",
    action: "update",
    possession: "any",
  })
  async disconnectDescriptions(
    @common.Param() params: AssetWhereUniqueInput,
    @common.Body() body: AssetDescriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      descriptions: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
