/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BlockDailyService } from "../blockDaily.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BlockDailyCreateInput } from "./BlockDailyCreateInput";
import { BlockDailyWhereInput } from "./BlockDailyWhereInput";
import { BlockDailyWhereUniqueInput } from "./BlockDailyWhereUniqueInput";
import { BlockDailyFindManyArgs } from "./BlockDailyFindManyArgs";
import { BlockDailyUpdateInput } from "./BlockDailyUpdateInput";
import { BlockDaily } from "./BlockDaily";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BlockDailyControllerBase {
  constructor(
    protected readonly service: BlockDailyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BlockDaily })
  @nestAccessControl.UseRoles({
    resource: "BlockDaily",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: BlockDailyCreateInput
  ): Promise<BlockDaily> {
    return await this.service.create({
      data: data,
      select: {
        averageBlockSize: true,
        id: true,
        createdAt: true,
        updatedAt: true,
        date: true,
        averageBlockTimeMs: true,
        blocksCount: true,
        blocksWithGraffitiCount: true,
        cumulativeUniqueGraffiti: true,
        transactionsCount: true,
        chainSequence: true,
        uniqueGraffitiCount: true,
        averageDifficulty: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BlockDaily] })
  @ApiNestedQuery(BlockDailyFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BlockDaily",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<BlockDaily[]> {
    const args = plainToClass(BlockDailyFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        averageBlockSize: true,
        id: true,
        createdAt: true,
        updatedAt: true,
        date: true,
        averageBlockTimeMs: true,
        blocksCount: true,
        blocksWithGraffitiCount: true,
        cumulativeUniqueGraffiti: true,
        transactionsCount: true,
        chainSequence: true,
        uniqueGraffitiCount: true,
        averageDifficulty: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BlockDaily })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BlockDaily",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: BlockDailyWhereUniqueInput
  ): Promise<BlockDaily | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        averageBlockSize: true,
        id: true,
        createdAt: true,
        updatedAt: true,
        date: true,
        averageBlockTimeMs: true,
        blocksCount: true,
        blocksWithGraffitiCount: true,
        cumulativeUniqueGraffiti: true,
        transactionsCount: true,
        chainSequence: true,
        uniqueGraffitiCount: true,
        averageDifficulty: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BlockDaily })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BlockDaily",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: BlockDailyWhereUniqueInput,
    @common.Body() data: BlockDailyUpdateInput
  ): Promise<BlockDaily | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          averageBlockSize: true,
          id: true,
          createdAt: true,
          updatedAt: true,
          date: true,
          averageBlockTimeMs: true,
          blocksCount: true,
          blocksWithGraffitiCount: true,
          cumulativeUniqueGraffiti: true,
          transactionsCount: true,
          chainSequence: true,
          uniqueGraffitiCount: true,
          averageDifficulty: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BlockDaily })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BlockDaily",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: BlockDailyWhereUniqueInput
  ): Promise<BlockDaily | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          averageBlockSize: true,
          id: true,
          createdAt: true,
          updatedAt: true,
          date: true,
          averageBlockTimeMs: true,
          blocksCount: true,
          blocksWithGraffitiCount: true,
          cumulativeUniqueGraffiti: true,
          transactionsCount: true,
          chainSequence: true,
          uniqueGraffitiCount: true,
          averageDifficulty: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
