/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AssetDescriptionService } from "../assetDescription.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AssetDescriptionCreateInput } from "./AssetDescriptionCreateInput";
import { AssetDescriptionWhereInput } from "./AssetDescriptionWhereInput";
import { AssetDescriptionWhereUniqueInput } from "./AssetDescriptionWhereUniqueInput";
import { AssetDescriptionFindManyArgs } from "./AssetDescriptionFindManyArgs";
import { AssetDescriptionUpdateInput } from "./AssetDescriptionUpdateInput";
import { AssetDescription } from "./AssetDescription";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AssetDescriptionControllerBase {
  constructor(
    protected readonly service: AssetDescriptionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AssetDescription })
  @nestAccessControl.UseRoles({
    resource: "AssetDescription",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: AssetDescriptionCreateInput
  ): Promise<AssetDescription> {
    return await this.service.create({
      data: {
        ...data,

        asset: {
          connect: data.asset,
        },

        transaction: {
          connect: data.transaction,
        },
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        type: true,
        value: true,

        asset: {
          select: {
            id: true,
          },
        },

        transaction: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AssetDescription] })
  @ApiNestedQuery(AssetDescriptionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AssetDescription",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<AssetDescription[]> {
    const args = plainToClass(AssetDescriptionFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        type: true,
        value: true,

        asset: {
          select: {
            id: true,
          },
        },

        transaction: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AssetDescription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssetDescription",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: AssetDescriptionWhereUniqueInput
  ): Promise<AssetDescription | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        type: true,
        value: true,

        asset: {
          select: {
            id: true,
          },
        },

        transaction: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AssetDescription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssetDescription",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: AssetDescriptionWhereUniqueInput,
    @common.Body() data: AssetDescriptionUpdateInput
  ): Promise<AssetDescription | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          asset: {
            connect: data.asset,
          },

          transaction: {
            connect: data.transaction,
          },
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          type: true,
          value: true,

          asset: {
            select: {
              id: true,
            },
          },

          transaction: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AssetDescription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssetDescription",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: AssetDescriptionWhereUniqueInput
  ): Promise<AssetDescription | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          type: true,
          value: true,

          asset: {
            select: {
              id: true,
            },
          },

          transaction: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
